spring:
  application:
    name: resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9001/oauth2/jwks

server:
  port: 9002

logging:
  level:
    org.springframework.security: trace

---
# Profile specific configuration for 'test'
spring:
  config:
    activate:
      on-profile: test
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${mock.webserver.url}/.well-known/jwks.json